In [ ]:
# Encode categorical variables into numerical form

#EDA Example
import numpy as np
import pandas as pd
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

data = {'Transaction_ID': [1, 2, 3, 4, 5],
        'Quantity': [2, 1, 3, 4, 2],
        'Price_per_item': [10.50, 25.00, 5.75, 12.00, 15.50],
        'Customer_ID': ['C001', 'C002', 'C001', 'C003', 'C002']}

df = pd.DataFrame(data)

print(df)

   Transaction_ID  Quantity  Price_per_item Customer_ID
0               1         2           10.50        C001
1               2         1           25.00        C002
2               3         3            5.75        C001
3               4         4           12.00        C003
4               5         2           15.50        C002

In [ ]:
df['total_amount'] = df['Quantity']  * df['Price_per_item']
print(df)

   Transaction_ID  Quantity  Price_per_item Customer_ID  total_amount
0               1         2           10.50        C001         21.00
1               2         1           25.00        C002         25.00
2               3         3            5.75        C001         17.25
3               4         4           12.00        C003         48.00
4               5         2           15.50        C002         31.00

In [ ]:
df['Transaction_Date'] = pd.to_datetime(['2026-03-04', '2025-06-12', '2024-12-23', '2020-09-30', '2021-04-09'])


df['Transaction_year'] = df['Transaction_Date'].dt.year
df['Trascation_month'] = df['Transaction_Date'].dt.month
# df['Transaction_day_of_week'] = df
print(df)

   Transaction_ID  Quantity  Price_per_item Customer_ID  total_amount  \
0               1         2           10.50        C001         21.00
1               2         1           25.00        C002         25.00
2               3         3            5.75        C001         17.25
3               4         4           12.00        C003         48.00
4               5         2           15.50        C002         31.00

  Transaction_Date  Transaction_year  Trascation_month
0       2026-03-04              2026                 3
1       2025-06-12              2025                 6
2       2024-12-23              2024                12
3       2020-09-30              2020                 9
4       2021-04-09              2021                 4

In [ ]:
df_encoded = pd.get_dummies(df,columns=['Customer_ID'], prefix='Customer', dtype=int)

#get_dummies() is a Pandas function that helps you convert categorical variables into numeric form by creating dummy/indicator variables.

print("DataFrame with one hot encoded 'Customer_ID:")
df_encoded

DataFrame with one hot encoded 'Customer_ID:

,Transaction_ID,Quantity,Price_per_item,total_amount,Transaction_Date,Transaction_year,Trascation_month,Customer_C001,Customer_C002,Customer_C003
0,1,2,10.50,21.00,2026-03-04,2026,3,1,0,0
1,2,1,25.00,25.00,2025-06-12,2025,6,0,1,0
2,3,3,5.75,17.25,2024-12-23,2024,12,1,0,0
3,4,4,12.00,48.00,2020-09-30,2020,9,0,0,1
4,5,2,15.50,31.00,2021-04-09,2021,4,0,1,0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
import warnings
warnings.filterwarnings('ignore')

df2 = pd.read_csv('/content/car_prices_ohe.csv')

df2

     brand  engine_size    price
0   Toyota          1.8  1800000
1     Ford          2.0  1700000
2      BMW          3.0  3200000
3   Toyota          2.0  1850000
4     Ford          2.2  1720000
5      BMW          3.2  3400000
6   Toyota          1.6  1600000
7     Ford          2.1  1750000
8      BMW          3.1  3300000
9   Toyota          1.9  1780000
10    Ford          2.3  1740000
11     BMW          3.3  3500000
12  Toyota          1.7  1650000
13    Ford          2.4  1760000
14     BMW          3.4  3600000
15  Toyota          2.1  1820000
16    Ford          2.5  1800000

In [ ]:
print('Unique brands:', df2['brand'].unique())

Unique brands: ['Toyota' 'Ford' 'BMW']

In [ ]:
df2.describe()

       engine_size         price
count    17.000000  1.700000e+01
mean      2.388235  2.233529e+06
std       0.591484  7.824157e+05
min       1.600000  1.600000e+06
25%       2.000000  1.740000e+06
50%       2.200000  1.800000e+06
75%       3.000000  3.200000e+06
max       3.400000  3.600000e+06

In [ ]:
df_dummies=pd.get_dummies(df2, columns=['brand'], dtype=int)
df_dummies.head()

   engine_size    price  brand_BMW  brand_Ford  brand_Toyota
0          1.8  1800000          0           0             1
1          2.0  1700000          0           1             0
2          3.0  3200000          1           0             0
3          2.0  1850000          0           0             1
4          2.2  1720000          0           1             0

In [ ]:
#avodidng the dummy variable trap

df_dummies = df_dummies.drop('brand_Toyota', axis=1)
df_dummies

    engine_size    price  brand_BMW  brand_Ford
0           1.8  1800000          0           0
1           2.0  1700000          0           1
2           3.0  3200000          1           0
3           2.0  1850000          0           0
4           2.2  1720000          0           1
5           3.2  3400000          1           0
6           1.6  1600000          0           0
7           2.1  1750000          0           1
8           3.1  3300000          1           0
9           1.9  1780000          0           0
10          2.3  1740000          0           1
11          3.3  3500000          1           0
12          1.7  1650000          0           0
13          2.4  1760000          0           1
14          3.4  3600000          1           0
15          2.1  1820000          0           0
16          2.5  1800000          0           1

In [ ]:
# x is engine size and brand
# y is price

In [ ]:
X = df_dummies.drop('price', axis=1)
y = df_dummies['price']
print(X)
print(y)
# model = LinearRegression()
# model.fit(X,y)

    engine_size  brand_BMW  brand_Ford
0           1.8          0           0
1           2.0          0           1
2           3.0          1           0
3           2.0          0           0
4           2.2          0           1
5           3.2          1           0
6           1.6          0           0
7           2.1          0           1
8           3.1          1           0
9           1.9          0           0
10          2.3          0           1
11          3.3          1           0
12          1.7          0           0
13          2.4          0           1
14          3.4          1           0
15          2.1          0           0
16          2.5          0           1
0     1800000
1     1700000
2     3200000
3     1850000
4     1720000
5     3400000
6     1600000
7     1750000
8     3300000
9     1780000
10    1740000
11    3500000
12    1650000
13    1760000
14    3600000
15    1820000
16    1800000
Name: price, dtype: int64

In [ ]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [ ]:
print('Model coeffecients:', model.coef_)
print("Model intercept:", model.intercept_)
print('R2 score:', model.score(X,y))

# y = bx+c = b1x1 + b2x2 + b3x3 + c

Model coeffecients: [ 470000. 1015500. -193000.]
Model intercept: 880500.0000000005
R2 score: 0.9941453558134759

In [ ]:
pred = model.predict([[2.2, 0,1]])
print(f'Predicted price of Ford 2.2L: ₹{pred[0]:.2f}')

Predicted price of Ford 2.2L: ₹1721500.00

In [ ]:
# prepare featrues and target
X2 = df2[['brand', 'engine_size']]
y2 = df2['price']

# OneHotEncoder with ColumnTransformer
ct=ColumnTransformer([
    ('brand_oheeeee', OneHotEncoder(drop='first'), ['brand'])                  # OneHotEncoder similar to get_dummies
], remainder='passthrough')

X2_encoded = ct.fit_transform(X2)           #never pass y
X2_encoded[:5]

array([[0. , 1. , 1.8],
       [1. , 0. , 2. ],
       [0. , 0. , 3. ],
       [0. , 1. , 2. ],
       [1. , 0. , 2.2]])

In [ ]:
model2 = LinearRegression()
model2.fit(X2_encoded, y2)

LinearRegression()

In [ ]:
print('Model coefficeints:', model2.coef_)
print('Model intercept:', model2.intercept_)
print('R2 score:', model2.score(X2_encoded, y2))

Model coefficeints: [-1208500. -1015500.   470000.]
Model intercept: 1895999.9999999981
R2 score: 0.9941453558134759

In [ ]:
pred2 = model2.predict([[1,0,3.0]])           #[brand_bmw, brand_ford, engine_size]
print(f'Predicted price of bmw 3.0L: ₹{pred2[0]:.2f}')

Predicted price of bmw 3.0L: ₹2097500.00

In [ ]:
# home assignment

df3 = pd.read_csv('/content/smartphone_prices.csv')

In [ ]:
| Feature             | ``pd.get_dummies`` | ``OneHotEncoder`` |
| ---                 | ---                | ---               |
| Library             | Pandas             | Scikit-learn      |
| Ease of use         | Very simple        | More setup        |
| Output type         | DataFrame          | Numpy array / sparse matrix |
| ML pipeline support | Limited            | Full integration  |
| Handles unseen data | No                 | Yes (with options)|